rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::SingleCBoardExample -> single_cboard_hardware

      - rmcs_core::example::RemoteControllerExample -> remote_controller_example

      - rmcs_core::controller::pid::PidController -> m2006_no_1_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> m2006_no_2_velocity_pid_controller

      - rmcs_core::controller::pid::PidController -> m2006_no_1_pitch_pid_controller
      - rmcs_core::controller::pid::PidController -> m2006_no_2_angle_pid_controller

      - rmcs_core::broadcaster::ValueBroadcaster -> gantry_value_broadcaster




single_cboard_hardware:
  ros__parameters:
    usb_pid: -1
    balance_flag: 0
    set_target_pitch: 0.5

remote_controller_example:
  ros__parameters:
    now_pitch: /example/gantry/gantry_now_pitch
    now_roll: /example/gantry/gantry_now_roll
    remote_left_switch: /example/remote_controller/left_switch
    remote_right_switch: /example/remote_controller/right_switch
    m2006_no_1_angle: /example/m2006_no_1/angle
    m2006_no_2_angle: /example/m2006_no_2/angle
    control_m2006_no_1_pitch: /example/m2006_no_1/control_m2006_no_1_pitch
    control_angle: /example/m2006_no_2/control_angle
    angle_error_ki: 0.000766989746
    control_angle_error_kp: 80.0    

m2006_no_1_velocity_pid_controller:
  ros__parameters:
    setpoint: /example/m2006_no_1/control_velocity
    measurement: /example/m2006_no_1/velocity
    control: /example/m2006_no_1/control_torque
    kp: 0.5
    ki: 0.0
    kd: 0.0

m2006_no_2_velocity_pid_controller:
  ros__parameters:
    setpoint: /example/m2006_no_2/control_velocity
    measurement: /example/m2006_no_2/velocity
    control: /example/m2006_no_2/control_torque
    kp: 0.5
    ki: 0.0
    kd: 0.0

m2006_no_1_pitch_pid_controller:
  ros__parameters:
    setpoint: /example/gantry/set_target_pitch_
    measurement: /example/gantry/gantry_now_pitch
    control: /example/m2006_no_1/control_m2006_no_1_pitch
    kp: 400.0
    ki: 0.0
    kd: 0.0

m2006_no_2_angle_pid_controller:
  ros__parameters:
    setpoint: /example/m2006_no_1/angle
    measurement: /example/m2006_no_2/angle
    control: /example/m2006_no_2/control_angle
    kp: 80.0
    ki: 0.0
    kd: 0.0

gantry_value_broadcaster:
  ros__parameters:
    forward_list:
      - /example/gantry/gantry_now_pitch
      - /example/gantry/gantry_now_roll
      - /example/m2006_no_1/control_velocity
      - /example/m2006_no_1/control_torque
      - /example/m2006_no_2/control_torque

      - /example/gantry/set_target_pitch_
      - /example/m2006_no_1/control_m2006_no_1_pitch
